apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 80
  externalIPs:
    - 192.168.31.46
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: public.ecr.aws/i7m0t5d2/2048game:latest
        ports:
        - containerPort: 80
